# Custom Dockerfile for VPS build
# This works with builds done on the VPS using yarn workspace
FROM node:22-bookworm-slim

WORKDIR /app

# Copy built server directory
COPY ./packages/backend/server /app
COPY ./packages/frontend/apps/web/dist /app/static
COPY ./packages/frontend/admin/dist /app/static/admin
COPY ./packages/frontend/apps/mobile/dist /app/static/mobile

# Install runtime dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl libjemalloc2 && \
    rm -rf /var/lib/apt/lists/*

# Enable corepack and install dependencies from server's package.json
RUN corepack enable && \
    yarn install --production && \
    yarn cache clean

# Enable jemalloc
ENV LD_PRELOAD=libjemalloc.so.2


EXPOSE 3010

CMD ["node", "./dist/main.js"]

